# Backend Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deploy
  namespace: dev
  labels:
    app: node-app

spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0

  selector:
    matchLabels:
      app: node-app
  template:
    metadata:
      labels:
        app: node-app
    spec:
      containers:
      - name: node
        image: node:20-alpine
        imagePullPolicy: IfNotPresent
        ports:
        - name: backend-port
          containerPort: 8080
        command: ["sleep", "10000"]

        env:
        - name: DB_HOST
          value: mysql-svc
        - name: DB_PORT
          value: "3306"

        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: db-config
              key: MYSQL_DATABASE
        - name: DB_USER
          valueFrom:
            configMapKeyRef:
              name: db-config
              key: MYSQL_USER
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: MYSQL_PASSWORD

        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "250m"

        livenessProbe:
          exec:
            command: ["true"]
          initialDelaySeconds: 20
          periodSeconds: 15
        readinessProbe:
          exec:
            command: ["true"]
          initialDelaySeconds: 10
          periodSeconds: 5

---
# Backend Service
apiVersion: v1
kind: Service
metadata:
  name: backend-svc
  namespace: dev
  labels:
    app: node-app
spec:
  selector:
    app: node-app
  ports:
  - name: http
    port: 8080
    targetPort: backend-port
    protocol: TCP
